/*
 * Circulating currencies. country is where the currency comes from.
 * also holds other names and places a person might type.
 */
(function () {
  var BT = (window.BT = window.BT || {});
  BT.currencies = [
    { code: "AED", name: "UAE dirham", country: "United Arab Emirates", also: ["UAE", "Emirates", "Dubai", "Abu Dhabi"] },
    { code: "AFN", name: "Afghani", country: "Afghanistan" },
    { code: "ALL", name: "Lek", country: "Albania" },
    { code: "AMD", name: "Dram", country: "Armenia" },
    { code: "ANG", name: "Netherlands Antillean guilder", country: "Curaçao", also: ["Sint Maarten", "Curacao"] },
    { code: "AOA", name: "Kwanza", country: "Angola" },
    { code: "ARS", name: "Argentine peso", country: "Argentina" },
    { code: "AUD", name: "Australian dollar", country: "Australia", also: ["Aussie"] },
    { code: "AWG", name: "Aruban florin", country: "Aruba" },
    { code: "AZN", name: "Azerbaijan manat", country: "Azerbaijan" },
    { code: "BAM", name: "Convertible mark", country: "Bosnia and Herzegovina", also: ["Bosnia"] },
    { code: "BBD", name: "Barbados dollar", country: "Barbados" },
    { code: "BDT", name: "Taka", country: "Bangladesh" },
    { code: "BGN", name: "Bulgarian lev", country: "Bulgaria", also: ["Lev"] },
    { code: "BHD", name: "Bahraini dinar", country: "Bahrain" },
    { code: "BIF", name: "Burundi franc", country: "Burundi" },
    { code: "BMD", name: "Bermudian dollar", country: "Bermuda" },
    { code: "BND", name: "Brunei dollar", country: "Brunei" },
    { code: "BOB", name: "Boliviano", country: "Bolivia" },
    { code: "BRL", name: "Real", country: "Brazil", also: ["Brasil"] },
    { code: "BSD", name: "Bahamian dollar", country: "Bahamas" },
    { code: "BTN", name: "Ngultrum", country: "Bhutan" },
    { code: "BWP", name: "Pula", country: "Botswana" },
    { code: "BYN", name: "Belarusian ruble", country: "Belarus" },
    { code: "BZD", name: "Belize dollar", country: "Belize" },
    { code: "CAD", name: "Canadian dollar", country: "Canada" },
    { code: "CDF", name: "Congolese franc", country: "Democratic Republic of the Congo", also: ["DRC", "DR Congo", "Congo Kinshasa"] },
    { code: "CHF", name: "Swiss franc", country: "Switzerland", also: ["Swiss", "Liechtenstein"] },
    { code: "CLP", name: "Chilean peso", country: "Chile" },
    { code: "CNY", name: "Yuan", country: "China", also: ["Chinese", "Renminbi", "RMB"] },
    { code: "COP", name: "Colombian peso", country: "Colombia" },
    { code: "CRC", name: "Costa Rican colon", country: "Costa Rica" },
    { code: "CUP", name: "Cuban peso", country: "Cuba" },
    { code: "CVE", name: "Cabo Verde escudo", country: "Cabo Verde", also: ["Cape Verde"] },
    { code: "CZK", name: "Czech koruna", country: "Czechia", also: ["Czech Republic"] },
    { code: "DJF", name: "Djibouti franc", country: "Djibouti" },
    { code: "DKK", name: "Danish krone", country: "Denmark", also: ["Greenland", "Faroe Islands"] },
    { code: "DOP", name: "Dominican peso", country: "Dominican Republic" },
    { code: "DZD", name: "Algerian dinar", country: "Algeria" },
    { code: "EGP", name: "Egyptian pound", country: "Egypt" },
    { code: "ERN", name: "Nakfa", country: "Eritrea" },
    { code: "ETB", name: "Birr", country: "Ethiopia" },
    { code: "EUR", name: "Euro", country: "Euro area", also: ["Europe", "France", "Germany", "Italy", "Spain", "Belgium", "Netherlands", "Portugal", "Austria", "Ireland", "Finland", "Greece", "Luxembourg", "Slovakia", "Slovenia", "Estonia", "Latvia", "Lithuania", "Croatia", "Cyprus", "Malta", "Bulgaria"] },
    { code: "FJD", name: "Fiji dollar", country: "Fiji" },
    { code: "FKP", name: "Falkland Islands pound", country: "Falkland Islands" },
    { code: "GBP", name: "Pound sterling", country: "United Kingdom", also: ["UK", "Britain", "England", "Scotland", "Wales", "Great Britain"] },
    { code: "GEL", name: "Lari", country: "Georgia" },
    { code: "GHS", name: "Ghanaian cedi", country: "Ghana" },
    { code: "GIP", name: "Gibraltar pound", country: "Gibraltar" },
    { code: "GMD", name: "Dalasi", country: "Gambia" },
    { code: "GNF", name: "Guinean franc", country: "Guinea" },
    { code: "GTQ", name: "Quetzal", country: "Guatemala" },
    { code: "GYD", name: "Guyanese dollar", country: "Guyana" },
    { code: "HKD", name: "Hong Kong dollar", country: "Hong Kong" },
    { code: "HNL", name: "Lempira", country: "Honduras" },
    { code: "HTG", name: "Gourde", country: "Haiti" },
    { code: "HUF", name: "Forint", country: "Hungary" },
    { code: "IDR", name: "Rupiah", country: "Indonesia" },
    { code: "ILS", name: "Israeli shekel", country: "Israel" },
    { code: "INR", name: "Indian rupee", country: "India" },
    { code: "IQD", name: "Iraqi dinar", country: "Iraq" },
    { code: "IRR", name: "Iranian rial", country: "Iran" },
    { code: "ISK", name: "Icelandic krona", country: "Iceland" },
    { code: "JMD", name: "Jamaican dollar", country: "Jamaica" },
    { code: "JOD", name: "Jordanian dinar", country: "Jordan" },
    { code: "JPY", name: "Yen", country: "Japan" },
    { code: "KES", name: "Kenyan shilling", country: "Kenya" },
    { code: "KGS", name: "Som", country: "Kyrgyzstan" },
    { code: "KHR", name: "Riel", country: "Cambodia" },
    { code: "KMF", name: "Comorian franc", country: "Comoros" },
    { code: "KPW", name: "North Korean won", country: "North Korea" },
    { code: "KRW", name: "South Korean won", country: "South Korea", also: ["Korea"] },
    { code: "KWD", name: "Kuwaiti dinar", country: "Kuwait" },
    { code: "KYD", name: "Cayman Islands dollar", country: "Cayman Islands" },
    { code: "KZT", name: "Tenge", country: "Kazakhstan" },
    { code: "LAK", name: "Kip", country: "Laos" },
    { code: "LBP", name: "Lebanese pound", country: "Lebanon" },
    { code: "LKR", name: "Sri Lankan rupee", country: "Sri Lanka" },
    { code: "LRD", name: "Liberian dollar", country: "Liberia" },
    { code: "LSL", name: "Loti", country: "Lesotho" },
    { code: "LYD", name: "Libyan dinar", country: "Libya" },
    { code: "MAD", name: "Moroccan dirham", country: "Morocco" },
    { code: "MDL", name: "Moldovan leu", country: "Moldova" },
    { code: "MGA", name: "Ariary", country: "Madagascar" },
    { code: "MKD", name: "Denar", country: "North Macedonia", also: ["Macedonia"] },
    { code: "MMK", name: "Kyat", country: "Myanmar", also: ["Burma"] },
    { code: "MNT", name: "Tugrik", country: "Mongolia" },
    { code: "MOP", name: "Pataca", country: "Macao", also: ["Macau"] },
    { code: "MRU", name: "Ouguiya", country: "Mauritania" },
    { code: "MUR", name: "Mauritian rupee", country: "Mauritius" },
    { code: "MVR", name: "Rufiyaa", country: "Maldives" },
    { code: "MWK", name: "Malawian kwacha", country: "Malawi" },
    { code: "MXN", name: "Mexican peso", country: "Mexico" },
    { code: "MYR", name: "Ringgit", country: "Malaysia" },
    { code: "MZN", name: "Metical", country: "Mozambique" },
    { code: "NAD", name: "Namibian dollar", country: "Namibia" },
    { code: "NGN", name: "Naira", country: "Nigeria" },
    { code: "NIO", name: "Cordoba", country: "Nicaragua" },
    { code: "NOK", name: "Norwegian krone", country: "Norway" },
    { code: "NPR", name: "Nepalese rupee", country: "Nepal" },
    { code: "NZD", name: "New Zealand dollar", country: "New Zealand" },
    { code: "OMR", name: "Omani rial", country: "Oman" },
    { code: "PAB", name: "Balboa", country: "Panama" },
    { code: "PEN", name: "Sol", country: "Peru" },
    { code: "PGK", name: "Kina", country: "Papua New Guinea" },
    { code: "PHP", name: "Philippine peso", country: "Philippines" },
    { code: "PKR", name: "Pakistani rupee", country: "Pakistan" },
    { code: "PLN", name: "Zloty", country: "Poland" },
    { code: "PYG", name: "Guarani", country: "Paraguay" },
    { code: "QAR", name: "Qatari riyal", country: "Qatar" },
    { code: "RON", name: "Romanian leu", country: "Romania" },
    { code: "RSD", name: "Serbian dinar", country: "Serbia" },
    { code: "RUB", name: "Russian ruble", country: "Russia" },
    { code: "RWF", name: "Rwandan franc", country: "Rwanda" },
    { code: "SAR", name: "Saudi riyal", country: "Saudi Arabia", also: ["Saudi"] },
    { code: "SBD", name: "Solomon Islands dollar", country: "Solomon Islands" },
    { code: "SCR", name: "Seychellois rupee", country: "Seychelles" },
    { code: "SDG", name: "Sudanese pound", country: "Sudan" },
    { code: "SEK", name: "Swedish krona", country: "Sweden" },
    { code: "SGD", name: "Singapore dollar", country: "Singapore" },
    { code: "SHP", name: "Saint Helena pound", country: "Saint Helena" },
    { code: "SLE", name: "Leone", country: "Sierra Leone" },
    { code: "SOS", name: "Somali shilling", country: "Somalia" },
    { code: "SRD", name: "Surinamese dollar", country: "Suriname" },
    { code: "SSP", name: "South Sudanese pound", country: "South Sudan" },
    { code: "STN", name: "Dobra", country: "Sao Tome and Principe" },
    { code: "SVC", name: "Salvadoran colon", country: "El Salvador" },
    { code: "SYP", name: "Syrian pound", country: "Syria" },
    { code: "SZL", name: "Lilangeni", country: "Eswatini", also: ["Swaziland"] },
    { code: "THB", name: "Baht", country: "Thailand" },
    { code: "TJS", name: "Somoni", country: "Tajikistan" },
    { code: "TMT", name: "Turkmenistan manat", country: "Turkmenistan" },
    { code: "TND", name: "Tunisian dinar", country: "Tunisia" },
    { code: "TOP", name: "Paanga", country: "Tonga" },
    { code: "TRY", name: "Turkish lira", country: "Turkey", also: ["Turkiye"] },
    { code: "TTD", name: "Trinidad and Tobago dollar", country: "Trinidad and Tobago" },
    { code: "TWD", name: "New Taiwan dollar", country: "Taiwan" },
    { code: "TZS", name: "Tanzanian shilling", country: "Tanzania" },
    { code: "UAH", name: "Hryvnia", country: "Ukraine" },
    { code: "UGX", name: "Ugandan shilling", country: "Uganda" },
    { code: "USD", name: "US dollar", country: "USA", also: ["United States", "US", "America", "Ecuador", "El Salvador", "Puerto Rico", "Timor-Leste"] },
    { code: "UYU", name: "Uruguayan peso", country: "Uruguay" },
    { code: "UZS", name: "Uzbekistan som", country: "Uzbekistan" },
    { code: "VES", name: "Bolivar", country: "Venezuela" },
    { code: "VND", name: "Dong", country: "Vietnam" },
    { code: "VUV", name: "Vatu", country: "Vanuatu" },
    { code: "WST", name: "Tala", country: "Samoa" },
    { code: "XAF", name: "Central African CFA franc", country: "Central Africa", also: ["Cameroon", "Central African Republic", "Chad", "Congo", "Equatorial Guinea", "Gabon", "CFA"] },
    { code: "XCG", name: "Caribbean guilder", country: "Curaçao", also: ["Sint Maarten", "Curacao"] },
    { code: "XCD", name: "East Caribbean dollar", country: "East Caribbean", also: ["Antigua", "Dominica", "Grenada", "Saint Lucia", "Saint Kitts", "Saint Vincent", "Anguilla", "Montserrat"] },
    { code: "XOF", name: "West African CFA franc", country: "West Africa", also: ["Benin", "Burkina Faso", "Cote d'Ivoire", "Ivory Coast", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo", "CFA"] },
    { code: "XPF", name: "CFP franc", country: "French Pacific", also: ["French Polynesia", "New Caledonia", "Tahiti"] },
    { code: "YER", name: "Yemeni rial", country: "Yemen" },
    { code: "ZAR", name: "Rand", country: "South Africa" },
    { code: "ZMW", name: "Zambian kwacha", country: "Zambia" },
    { code: "ZWG", name: "Zimbabwe gold", country: "Zimbabwe" }
  ];
})();
